source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'FalconAppTest' do
  pod 'Falcon-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/falcon/falcon-ios/binding/ios/Falcon-iOS.podspec'
end

target 'FalconAppTestUITests' do
  pod 'Falcon-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/falcon/falcon-ios/binding/ios/Falcon-iOS.podspec'
end

target 'PerformanceTest' do
  pod 'Falcon-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/falcon/falcon-ios/binding/ios/Falcon-iOS.podspec'
end
